version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

  post_build:
    commands:
      - aws logs get-log-events --log-group-name /aws/codebuild/justbuild --log-stream-name $(aws codebuild batch-get-builds --ids $CODEBUILD_BUILD_ID --query 'builds[].logs.streamName' --output text) --query 'events[].message' --output text > build_and_cloudwatch_logs.txt
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" == "1" ]; then
          # Publish build logs to SNS topic
          aws sns publish --topic-arn arn:aws:sns:us-east-1:932757591213:buildsuccess --subject "Build Logs Notification" --message "Build logs attached." --message file://build_and_cloudwatch_logs.txt
        fi

artifacts:
  files:
    - '**/*'
